---
title: "Доклад по теме Современные методы криптографии"
subtitle: "Дисциплина: Архитектура компьютера"
author: "Володина Алиса Алексеевна"
---

# Введение

Криптография - наука о математических методах обеспечения конфиденциальности, целостности данных, аутентификации, шифрования.

Изначально криптография изучала методы шифрования информации - обратимого преобразования открытого (исходного) текста на основе секретного алгоритма или ключа в шифрованный текст (шифротекст). Традиционная криптография образует раздел симметричных криптосистем, в которых зашифровывание и расшифровывание проводится с использованием одного и того же секретного ключа.

Криптография, имеющая тысячелетнюю историю, переживает в настоящее время своеобразный этап: сосуществования трех разнородных ветвей и перехода от классической парадигмы к квантовой. Как область большой практической важности, развиваемая ведущими учеными разных специальностей, она требует системного изучения, в том числе с применением библиометрии, одна из важных функций которой - анализ структуры и динамики науки.

Для современной криптографии характерно использование открытых алгоритмов шифрования, предполагающих применение вычислительных средств. Известно более десятка проверенных алгоритмов шифрования, которые при использовании ключа достаточной длины и корректной реализации алгоритма являются криптографически стойкими.

# Распространенный алгоритмы шифрования

К числу распространённых алгоритмов относятся:

симметричные: DES, AES, ГОСТ 28147-89, ГОСТ 34.12-2018, Camellia, Twofish, Blowfish, IDEA, RC4 и другие;

асимметричные: RSA и Elgamal (Эль-Гамаль);

хеш-функции: SHA-2, SHA-3, ГОСТ Р 34.11-2012 («Стрибог»).

Современная криптография является динамично развивающейся областью, которая сочетает три направления: классическую, пост-квантовую и квантовую криптографию.

Криптографические методы стали широко использоваться частными лицами в электронных коммерческих операциях, телекоммуникациях и многих других средах.

#Национальные стандарты шифрования

Во многих странах приняты национальные стандарты шифрования.

В США в 2001 году принят стандарт симметричного шифрования AES на основе алгоритма Rijndael с длиной ключа 128, 192 и 256 бит. Алгоритм AES пришёл на смену прежнему алгоритму DES, который теперь рекомендовано использовать только в режиме Triple DES.

В Российской Федерации действует стандарт ГОСТ 34.12-2015 с режимами шифрования блока сообщения длиной 64 («Магма») и 128 («Кузнечик») битов, и длиной ключа 256 бит. Также для создания цифровой подписи используется алгоритм ГОСТ Р 34.10-2012.

# Примитивы и стандарты криптографии

В основе построения криптостойких систем лежит многократное использование относительно простых преобразований, так называемых криптографических примитивов.

Клод Шеннон, известный американский математик и электротехник, предложил использовать подстановки (substitution) и перестановки (permutation). Схемы, которые реализуют эти преобразования, называются SP-сетями. Нередко используемыми криптографическими примитивами являются также преобразования типа циклический сдвиг или гаммирование.

Ниже приведены основные криптографические примитивы и примеры их использования.

Симметричное шифрование. Заключается в том, что обе стороны-участники обмена данными имеют абсолютно одинаковые ключи для шифрования и расшифровки данных. Данный способ осуществляет преобразование, позволяющее предотвратить просмотр информации третьей стороной. Пример: книжный шифр.

Асимметричное шифрование. Предполагает использовать в паре два разных ключа - открытый и секретный (закрытый). В асимметричном шифровании ключи работают в паре - если данные шифруются открытым ключом, то расшифровать их можно только соответствующим секретным ключом, и наоборот - если данные шифруются секретным ключом, то расшифровать их можно только соответствующим открытым ключом. Использовать открытый ключ из одной пары и секретный с другой - невозможно. Каждая пара асимметричных ключей связана математическими зависимостями. Данный способ также нацелен на преобразование информации от просмотра третьей стороной.

Цифровые подписи. Цифровые подписи используют для установления подлинности документа, его происхождения и авторства, их использование исключает искажения информации в электронном документе.

Хеширование. Преобразование входного массива данных произвольной длины в выходную битовую строку фиксированной длины. Такие преобразования также называются хеш-функциями или функциями свёртки, а их результаты называют хеш-кодом, контрольной суммой или дайджестом сообщения (message digest). Результаты хеширования статистически уникальны. Последовательность, отличающаяся хотя бы одним байтом, не будет преобразована в то же самое значение.

# S-боксы и нелинейность

Важнейшим элементом SP-сетей является S-бокс (s-box) - узел замены, который обеспечивает нелинейность шифра. Именно нелинейность делает криптоанализ сложным.

Пособие Казанского федерального университета определяет S-бокс как отображение из пространства векторов размерности nn в пространство размерности mm. Чем выше степень нелинейности (NL) S-бокса, тем успешнее он противостоит атакам. Идеальными с этой точки зрения являются bent-функции, имеющие максимально возможную нелинейность (для n=6n=6 максимальная нелинейность составляет 28).

На основе этих примитивов строятся национальные стандарты: в США - стандарт AES, пришедший на смену устаревшему DES; в России - стандарт ГОСТ 34.12-2015 с блочными шифрами «Магма» и «Кузнечик», а для цифровой подписи - ГОСТ Р 34.10-2012.

# Криптоанализ и методы атак

Существует два вида симметричных шифров, используемых в криптографии - это потоковые и блочные шифры.

Потоковые шифры шифруют поток информации посимвольно, складывая побайтно или побитово информационный поток с ключевой последовательностью.

# Блочные шифры

Блочные шифры разбивают текст на блоки определенной длины (обычно 64, 128 и более бит) и используют схему Фейстеля или подобные для перестановок и смешивания ключей внутри каждого блока в ходе многораундовых процедур.

В свою очередь, для потоковых шифров ключевая последовательность строится либо как одноразовый блокнот, когда при каждом шифровании заново используется новый ключ (например, построенный на фрагменте какого-то литературного произведения), либо используется генератор псевдослучайной последовательности, когда ключ небольшой длины может генерировать псевдослучайную последовательность большого периода. Ключевая последовательность, получаемая с помощью таких генераторов, должна удовлетворять ряду требований, которые позволяют успешно противостоять различным видам криптографических атак. Требования к псевдослучайным последовательностям изложены в тестах американского Института стандартов NIST.

Блочные шифры используют, в основном, схему Фейстеля, разработанную еще в 70-х годах XX столетия. В 1971 году Хорст Фейстель запатентовал два устройства, реализующих различные алгоритмы шифрования, позже получившие название «Люцифер». Тогда Фейстель работал над созданием новых криптосистем в компании IBM вместе с Доном Копперсмитом. Проект «Люцифер» был экспериментальным, но стал основой для алгоритма DES (Data Encryption Standard).

Любой блочный шифр разбивает шифруемый файл на блоки фиксированной длины (например, для DES он был равен 64 битам) и выполняет многораундовые преобразования, состоящие из однотипных преобразований, включающих подстановки, перестановки и гаммирование. Гаммирование - это сложение блока данных с ключевой последовательностью, такое же, как в потоковых шифрах.

# Линейный криптоанализ

Преобразование называется линейным, если оно может быть выражено с помощью набора линейных функций fj(x1,x2,…,xn), j=1,2,…,kfj​(x1​,x2​,…,xn​), j=1,2,…,k. Линейными называются функции вида f(x1,x2,…,xn)=a1x1+a2x2+⋯+anxn+bf(x1​,x2​,…,xn​)=a1​x1​+a2​x2​+⋯+an​xn​+b.

Перестановки и гаммирование – это линейные преобразования, а подстановки - нелинейные.

Линейный криптоанализ - это вид атаки, позволяющий находить ключ шифрования путем анализа входных и выходных блоков данных.

Произвольный s-бокс представляет собой отображение из пространства векторов размерности nn с элементами из Z2={0,1}Z2​={0,1} в пространство векторов размерности mm с такими же элементами с определенными свойствами. S-бокс может быть задан либо как перестановка векторов, либо как набор mm булевых функций от nn переменных. Каждый s-бокс характеризуется своей степенью нелинейности, которая определяется как наименьшее расстояние по Хэммингу между линейными комбинациями булевых функций, образующих s-бокс, и классом линейных булевых функций. Чем выше степень нелинейности s-бокса, тем успешнее s-бокс противостоит криптоатакам с использованием нелинейного криптоанализа.

#Перспективные направления: 

Наиболее перспективным направлением криптографии на данный момент является постквантовая криптография. Постквантовая криптография (PQC) - это методы защиты информации, стойкие к атакам как классических, так и будущих мощных квантовых компьютеров

# Проблема квантовых компьютеров

Традиционные методы шифрования на сегодняшний день отходят на второй план. Причина - появление квантовых компьютеров, машин, чья вычислительная мощность ставит под угрозу самые сложные из современных криптографических алгоритмов. В кибербезопасности появляется понятие «постквантовая криптография». Это не просто обновление старых протоколов, а принципиально новый подход к созданию цифровой безопасности.

Большинство современных систем шифрования основаны на сложности решения определенных математических задач - разложения больших чисел на множители или дискретного логарифмирования. Для классического компьютера эти задачи требуют огромного количества времени. Однако алгоритмы, запущенные на достаточно мощном квантовом компьютере, решают их с большой эффективностью, делая существующую защиту бесполезной.

# Что такое постквантовая криптография (PQC)

Постквантовая криптография (Post-Quantum Cryptography, PQC) - это не один алгоритм, а совокупность криптографических алгоритмов, которые устойчивы к атакам как с использованием классических, так и квантовых компьютеров.

Их принципиальное отличие заключается в том, что в основе лежат математические задачи, которые остаются сложными даже для квантового процессора. Вместо факторизации чисел PQC использует другие, более устойчивые к нападениям злоумышленников разделы математики.
Криптография на решётках (Lattice-based cryptography)

Наиболее перспективным и универсальным считается направление криптографии на решётках. Разберем его подробно далее, так как именно оно, с высокой вероятностью, ляжет в основу цифровой безопасности.

В математике решётка - это не периодическая структура, как в кристалле, а бесконечный набор точек в многомерном пространстве, упорядоченных с определенным шагом.

Принцип безопасности. Сложность, на которой строится безопасность, называется «задачей о кратчайшем векторе». Если дана многомерная решётка с тысячами измерений, необходимо найти в ней самую короткую линию, соединяющую две точки (самый короткий вектор). Для классического и для квантового компьютера эта задача является вычислительно неразрешимой при достаточно больших размерах решётки. Можно легко сгенерировать решётку с ключом (базисом), который позволяет легко ориентироваться в ней и решать задачу, но для внешнего наблюдателя без этого ключа поиск кратчайшего вектора осложнён, так как ключ находится в 1000-мерном пространстве.

Ключевые преимущества технологии:

Стойкость к квантовым атакам: на сегодняшний день не известно алгоритмов, которые бы эффективно взламывали хорошо подобранные решёточные системы на квантовом компьютере.

Гибкость и универсальность: на основе решёток можно построить все необходимые криптографические примитивы - асимметричное шифрование (для обмена ключами), цифровые подписи (для аутентификации).

Высокая производительность: алгоритмы на решётках, как правило, работают быстрее и требуют меньше вычислительных ресурсов, чем некоторые их конкуренты, что критически важно для высоконагруженных систем.

Области применения PQC

Внедрение PQC - это не просто замена одного алгоритма на другой. Это масштабная миграция всей цифровой экосистемы.

Защищенные коммуникации: браузеры, мессенджеры и VPN-сервисы будут использовать PQC-алгоритмы для установления безопасного соединения. Это гарантирует то, что перехваченное сегодня зашифрованное сообщение нельзя будет расшифровать завтра, когда квантовые компьютеры станут мощнее.

Цифровые подписи: юридически значимые документы, программное обеспечение и транзакции в блокчейне будут подписываться PQC-подписями. Это защитит их от подделки в будущем.

Долговременное хранение данных: информация, которая должна храниться долгое время в архивах (государственные архивы, медицинские карты, коммерческие секреты), тоже должна быть защищена. Уже сегодня такие данные должны шифроваться с использованием PQC, иначе они станут уязвимыми задолго до истечения своего срока конфиденциальности.

# Вызовы при переходе на PQC

Переход на постквантовую криптографию - сложнейшая задача. Основные вызовы включают:

Стандартизация - проведение конкурса на отбор лучших PQC-алгоритмов.

Совместимость — внедрение новых алгоритмов в миллиарды устройств по всему миру, от мощных серверов до крошечных IoT-датчиков.

Криптографическая гибкость — эксперты рекомендуют стратегию «квантовой миграции», когда системы используют и классические, и PQC-алгоритмы одновременно, создавая многоуровневую защиту.

Таким образом, постквантовая криптография — это стратегический и необходимый ответ на экзистенциальную угрозу квантовых вычислений. Она представляет собой переход от эпохи, когда наша безопасность основывалась на вычислительных ограничениях, к эпохе, где она будет базироваться на непреодолимой математической сложности.

# Заключение

Современная криптография прошла путь от искусства тайнописи до строгой математической науки, лежащей в основе глобальной цифровой безопасности.

Основные выводы:

Современные методы делятся на симметричные и асимметричные, а на практике используются их гибридные схемы. Эти методы лежат в основе защиты информации, которая сегодня является национальным вопросом.

Ключевую роль в обеспечении стойкости шифров играют нелинейные S-боксы, устойчивость которых оценивается с помощью линейного криптоанализа.

Развитие квантовых технологий ставит новые вызовы, требуя разработки постквантовых алгоритмов, в частности, на основе теории решёток, и открывает новые возможности с появлением квантовой криптографии.

Практическое применение криптографии выходит далеко за рамки классических компьютерных систем, охватывая радиотехнику и другие сферы.

Криптография остается динамично развивающейся областью, которая будет определять лицо информационной безопасности в ближайшие десятилетия.

# Список литературы{.unnumbered}

1. Криптография // Википедия. — URL: https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F (дата обращения: 29.03.2026).

2. Линейный криптоанализ : учеб.-метод. пособие / Казан. федер. ун-т. — 2025. — URL: https://dspace.kpfu.ru/xmlui/bitstream/handle/net/185431/F_UMP_Linejnyj_kript_2025.pdf (дата обращения: 29.03.2026).

3. Развитие квантовой криптографии: краткий обзор и библиометрический анализ. — URL: file:///home/aavolodina/Downloads/razvitie-kvantovoy-kriptografii-kratkiy-obzor-i-bibliometricheskiy-analiz.pdf (дата обращения: 29.03.2026).

4. [Название статьи] // Военный вестник. — URL: https://voenvestnik.ru/30ES925.html (дата обращения: 29.03.2026).


